# Generated by Django 5.1.3 on 2024-11-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=60)),
                ('id_prov', models.CharField(max_length=6)),
                ('cant', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desc', models.CharField(max_length=400)),
                ('id_suc', models.CharField(max_length=6)),
            ],
        ),
    ]
