# Generated by Django 5.1 on 2024-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_suc', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('CP', models.IntegerField(max_length=20)),
                ('web', models.CharField(max_length=20)),
            ],
        ),
    ]
