# Generated by Django 5.1 on 2024-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('ide', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sueldo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
            ],
        ),
    ]
